services:
  database-cassandra:
    container_name: ${DATABASE_CASSANDRA_CONTAINER_NAME}
    image: cassandra:latest
    environment:
      CASSANDRA_USER: ${DATABASE_CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${DATABASE_CASSANDRA_PASSWORD}
    ports:
      - ${DATABASE_CASSANDRA_PORT}:9042
    volumes:
      - database-cassandra:/var/lib/cassandra
    restart: ${DATABASE_CASSANDRA_CONTAINER_RESTART}
    healthcheck:
      test: cqlsh -u ${DATABASE_CASSANDRA_USER} -p ${DATABASE_CASSANDRA_PASSWORD} -e 'describe cluster'
      interval: 12s
      timeout: 12s
      retries: 12

  tgo:
    container_name: ${TGO_CONTAINER_NAME}
    image: ${TGO_IMAGE_TAG}
    build:
      context: ..
      dockerfile: deployments/Dockerfile
      target: ${TGO_IMAGE_BUILD_TARGET}
    environment:
      DATABASE_CASSANDRA_HOSTNAME: database-cassandra
      DATABASE_CASSANDRA_PORT: 9042
      DATABASE_CASSANDRA_USER: ${DATABASE_CASSANDRA_USER}
      DATABASE_CASSANDRA_PASSWORD: ${DATABASE_CASSANDRA_PASSWORD}
      DATABASE_CASSANDRA_KEYSPACE: ${DATABASE_CASSANDRA_KEYSPACE}
      TGO_API_COINGECKO_DEMO_KEY: ${TGO_API_COINGECKO_DEMO_KEY}
      TGO_SERVER_ECHO_HOSTNAME: ${TGO_SERVER_ECHO_HOSTNAME}
      TGO_SERVER_ECHO_PORT: ${TGO_SERVER_ECHO_PORT}
      TGO_SERVER_ECHO_URL: ${TGO_SERVER_ECHO_URL}
      TGO_SERVER_ECHO_MODE: ${TGO_SERVER_ECHO_MODE}
      TGO_SERVER_ECHO_ALLOWED_HOSTS: ${TGO_SERVER_ECHO_ALLOWED_HOSTS}
      TGO_DEV_AIR_PROXY_PORT: ${TGO_DEV_AIR_PROXY_PORT}
    command: ${TGO_CONTAINER_START}
    ports:
      - ${TGO_SERVER_ECHO_PORT}:${TGO_SERVER_ECHO_PORT}
      - ${TGO_DEV_AIR_PROXY_PORT}:${TGO_DEV_AIR_PROXY_PORT}
    volumes:
      - ${TGO_CONTAINER_VOLUME}
      - tgo-modules:/go/pkg/mod
    restart: ${TGO_CONTAINER_RESTART}
    depends_on:
      database-cassandra:
        condition: service_healthy

volumes:
  database-cassandra:
    name: ${DATABASE_CASSANDRA_CONTAINER_VOLUME}
  tgo-logs:
    name: tgo-logs
  tgo-modules:
    name: tgo-modules

networks:
  default:
    name: tgo
