// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

var CreateFormTagId = "create"

func CreateFormInit(formTagId string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_CreateFormInit_5d00`,
		Function: `function __templ_CreateFormInit_5d00(formTagId){$(` + "`" + `#${formTagId}` + "`" + `)
        .form({
            on: "blur",
            inline: true,
            preventLeaving: true,
            keyboardShortcuts: false,
            fields: {
                Username: {
                    rules: [
                        {
                            type: "size[2..20]"
                        },
                        {
                            type: "regExp[/^[A-Za-z0-9]+$/]",
                            prompt: "{name} must be alphanumeric only"
                        },
                        {
                            type: "regExp[/^.*[^0-9].*$/]",
                            prompt: "{name} cannot be only numbers"
                        }
                    ]
                },
                "Portfolio[Currency]": {
                    rules: [
                        {
                            type: "exactCount[1]",
                        },
                    ]
                },
                "Portfolio[Coins]": {
                    rules: [
                        {
                            type: "minCount[1]",
                        },
                        {
                            type: "maxCount[10]",
                        }
                    ]
                },
                Terms: {
                    rules: [
                        {
                            type: "checked",
                            prompt: "Terms & Conditions must be checked"
                        }
                    ]
                }
            }
        })
        .api({
            action: "user_create", 
            method: "PUT",
            beforeSend: function(settings) {
                list = settings.data.Portfolio.Coins;

                coins = _.split(list, ",", -1);

                settings.data.Portfolio.Coins = coins;

                settings.data = JSON.stringify(settings.data);

                return settings;
            },
            onSuccess: function(response, element, xhr) {
                $.toast({
                    class: "success",
                    message: response.Message,
                    showProgress: "top",
                });

                _.delay(function() {
                    $(` + "`" + `#${formTagId}` + "`" + `).form("reset");
                }, 1000);
            },
            onFailure: function(response, element, xhr) {
                $.toast({
                    class: "error",
                    message: response.Message,
                    showProgress: "top"
                });
            }
        })
    ;
}`,
		Call:       templ.SafeScript(`__templ_CreateFormInit_5d00`, formTagId),
		CallInline: templ.SafeScriptInline(`__templ_CreateFormInit_5d00`, formTagId),
	}
}

func ShowTerms(modalTagId string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ShowTerms_9e12`,
		Function: `function __templ_ShowTerms_9e12(modalTagId){$(` + "`" + `#${modalTagId}` + "`" + `).modal("show");
}`,
		Call:       templ.SafeScript(`__templ_ShowTerms_9e12`, modalTagId),
		CallInline: templ.SafeScriptInline(`__templ_ShowTerms_9e12`, modalTagId),
	}
}

func CreateForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(CreateFormTagId)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/app/server/component/page/home/form.create.templ`, Line: 96, Col: 27}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"ui inverted form\"><div class=\"required field\"><label>Username</label><div class=\"ui inverted transparent left icon input\"><i class=\"user icon\"></i> <input type=\"text\" placeholder=\"Username\" name=\"Username\"></div></div><label>Portfolio</label><div class=\"ui divider\"></div><div class=\"required field\"><label>Currency</label><div id=\"currency\" class=\"ui inverted fluid multiple search selection dropdown\"><input type=\"hidden\" name=\"Portfolio[Currency]\"><div class=\"default text\"><i class=\"money bill wave icon\"></i> USD, EUR, RUB...</div></div></div><div class=\"required field\"><label>Coins</label><div id=\"coins\" class=\"ui inverted fluid multiple search selection dropdown\"><input type=\"hidden\" name=\"Portfolio[Coins]\"><div class=\"default text\"><i class=\"monero icon\"></i> Monero, Bitcoin, Ethereum...</div></div></div><div class=\"ui divider\"></div><div class=\"ui middle aligned center aligned grid\"><div class=\"column\"><div class=\"inline required field\"><div class=\"ui inverted checkbox\"><input type=\"checkbox\" name=\"Terms\"> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, ShowTerms(TermsModalTagId))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label style=\"cursor: pointer;\" onclick=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 templ.ComponentScript = ShowTerms(TermsModalTagId)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">I agree to the <a><b>terms and conditions</b></a></label></div></div><button class=\"ui vertical animated fluid primary submit button\"><div class=\"hidden content\"><i class=\"upload icon\"></i></div><div class=\"visible content\">Create</div></button></div></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CreateFormInit(CreateFormTagId).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
